version: '3.8'

services:
  downloader_mp3-flask:
    container_name: downloader_mp3
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ${HOME}/.secrets/bot_telegram_mp3/.env:/app/.env:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
