version: '3.8'

services:
  downloader_mp3-flask:
    container_name: downloader_mp3
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
